name: Update JSON stats
on:
  schedule:
    - cron: '15 02 * * *'
  workflow_dispatch:
  
jobs:
  run:
    name: Get JSON and update
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Get SF1
        run: |
          H='sistemas.trf1.jus.br/pgp-api/api/local/JFDF/processo'
          P='1023891-47.2023.4.01.3400'
          T='ordem=1&max=10&offset=0'
          F='SF1'
          curl -s "https://$H/$P?$T" \
          -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8' \
          -H 'Accept-Language: en;q=0.9' \
          -H 'Cache-Control: no-cache' \
          -H 'Connection: keep-alive' \
          -H 'Cookie: SISTEMAS-47873-SG_PGP_API_8080_TCP=FFABBAKMJABP; SISTEMAS-47873-SG_ORDEMCRONOLOGICA_8080_TCP=EGACBAKMJABP'; TRF1_CHECK=$((1000000 + $RANDOM % 123456)) \
          -H 'DNT: 1' \
          -H 'Pragma: no-cache' \
          -H 'Sec-Fetch-Dest: document' \
          -H 'Sec-Fetch-Mode: navigate' \
          -H 'Sec-Fetch-Site: none' \
          -H 'Sec-Fetch-User: ?1' \
          -H 'Sec-GPC: 1' \
          -H 'Upgrade-Insecure-Requests: 1' \
          -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/$((100 + $RANDOM % 31)).$(($RANDOM % 9)).$(($RANDOM % 9)).$(($RANDOM % 9)) Safari/537.36' \
          -H 'sec-ch-ua: "Brave";v="131", "Chromium";v="131", "Not_A Brand";v="24"' \
          -H 'sec-ch-ua-mobile: ?0' \
          -H 'sec-ch-ua-platform: "macOS"' --output "$F.json"
          jq . "$F.json" > "json/$F/$GITHUB_RUN_ID.json" || echo "curl -s https://$H/$P?$T | jq" > "json/$F/$GITHUB_RUN_ID.json"
          cat "$F.json"

      - name: Commit SF1
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Charles Santos
          author_email: thyarles@gmail.com
          message: Adding SF1 JSON stats
          add: 'json/SF1/*.json'

      - name: Get CD1
        run: |
          H='sistemas.trf1.jus.br/pgp-api/api/local/JFDF/processo'
          P='1026558-69.2024.4.01.3400'
          T='ordem=1&max=10&offset=0'
          F='CD1'
          curl -s "https://$H/$P?$T" \
          -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8' \
          -H 'Accept-Language: en;q=0.9' \
          -H 'Cache-Control: no-cache' \
          -H 'Connection: keep-alive' \
          -H 'Cookie: SISTEMAS-47873-SG_PGP_API_8080_TCP=FFABBAKMJABP; SISTEMAS-47873-SG_ORDEMCRONOLOGICA_8080_TCP=EGACBAKMJABP'; TRF1_CHECK=$((1000000 + $RANDOM % 123456)) \
          -H 'DNT: 1' \
          -H 'Pragma: no-cache' \
          -H 'Sec-Fetch-Dest: document' \
          -H 'Sec-Fetch-Mode: navigate' \
          -H 'Sec-Fetch-Site: none' \
          -H 'Sec-Fetch-User: ?1' \
          -H 'Sec-GPC: 1' \
          -H 'Upgrade-Insecure-Requests: 1' \
          -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/$((100 + $RANDOM % 31)).$(($RANDOM % 9)).$(($RANDOM % 9)).$(($RANDOM % 9)) Safari/537.36' \
          -H 'sec-ch-ua: "Brave";v="131", "Chromium";v="131", "Not_A Brand";v="24"' \
          -H 'sec-ch-ua-mobile: ?0' \
          -H 'sec-ch-ua-platform: "macOS"' --output "$F.json"
          jq . "$F.json" > "json/$F/$GITHUB_RUN_ID.json" || echo "curl -s https://$H/$P?$T | jq" > "json/$F/$GITHUB_RUN_ID.json"
          cat "$F.json"


      - name: Commit CD1
        uses: EndBug/add-and-commit@v9
        with:
          author_name: Charles Santos
          author_email: thyarles@gmail.com
          message: Adding CD1 JSON stats
          add: 'json/CD1/*.json'      

      - name: Send error
        run: |
          jq . SF1.json
          jq . CD1.json
